const DATA = {"New York": {
    // "": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "1": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 1000},
    "2": {"url": "https://www.youtube.com/watch?v=-PMFbMvPFW4&t=8s&mode=theatre","width": "700", "loadInMs": 1000},
    "3": {"width": "300", "height": "322", "loadInMs": 1000},
    "4": {"url": "https://youtu.be/9Cqe7JfP8uA?t=11&mode=theatre&mute=1", "width": "900", "loadInMs": 1000},
    "5": {"width": "480", "height": "720", "loadInMs": 1000},
    // break
    "6": {"width": "https://www.youtube.com/watch?v=rm1NOlZzxVg&t=40s&mode=theatre", "height": "", "top": "", "left": "", "loadInMs": 1000},
    "7": {"width": "720", "height": "1080", "top": "", "left": "", "loadInMs": 3000},
    "8": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "9": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "10": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "11": {"width": "1000", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "12": {"width": "740", "height": "450", "top": "", "left": "", "loadInMs": 3000},
    "13": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "14": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "15": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "16": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "17": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "18": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "19": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "20": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "21": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "22": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "23": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "24": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "25": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "26": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "27": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "28": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "29": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "30": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "31": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "32": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "33": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "34": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
    "35": {"width": "", "height": "", "top": "", "left": "", "loadInMs": 3000},
}}